// Datos tomados exactamente de las tablas `paises` y `zonasHorarias`/`zonas_horarias`
// provistas por el usuario (BD.sql / data.sql). No editar a mano — si el catálogo
// cambia, regenerar desde la fuente original.

export const countries = [
  { isoCode: 'US', name: 'Estados Unidos', flagEmoji: '🇺🇸' },
  { isoCode: 'CA', name: 'Canadá', flagEmoji: '🇨🇦' },
  { isoCode: 'MX', name: 'México', flagEmoji: '🇲🇽' },
  { isoCode: 'GT', name: 'Guatemala', flagEmoji: '🇬🇹' },
  { isoCode: 'BZ', name: 'Belice', flagEmoji: '🇧🇿' },
  { isoCode: 'SV', name: 'El Salvador', flagEmoji: '🇸🇻' },
  { isoCode: 'HN', name: 'Honduras', flagEmoji: '🇭🇳' },
  { isoCode: 'NI', name: 'Nicaragua', flagEmoji: '🇳🇮' },
  { isoCode: 'CR', name: 'Costa Rica', flagEmoji: '🇨🇷' },
  { isoCode: 'PA', name: 'Panamá', flagEmoji: '🇵🇦' },
  { isoCode: 'CO', name: 'Colombia', flagEmoji: '🇨🇴' },
  { isoCode: 'VE', name: 'Venezuela', flagEmoji: '🇻🇪' },
  { isoCode: 'GY', name: 'Guyana', flagEmoji: '🇬🇾' },
  { isoCode: 'SR', name: 'Surinam', flagEmoji: '🇸🇷' },
  { isoCode: 'GF', name: 'Guayana Francesa', flagEmoji: '🇬🇫' },
  { isoCode: 'BR', name: 'Brasil', flagEmoji: '🇧🇷' },
  { isoCode: 'EC', name: 'Ecuador', flagEmoji: '🇪🇨' },
  { isoCode: 'PE', name: 'Perú', flagEmoji: '🇵🇪' },
  { isoCode: 'BO', name: 'Bolivia', flagEmoji: '🇧🇴' },
  { isoCode: 'PY', name: 'Paraguay', flagEmoji: '🇵🇾' },
  { isoCode: 'CL', name: 'Chile', flagEmoji: '🇨🇱' },
  { isoCode: 'AR', name: 'Argentina', flagEmoji: '🇦🇷' },
  { isoCode: 'UY', name: 'Uruguay', flagEmoji: '🇺🇾' },
  { isoCode: 'CU', name: 'Cuba', flagEmoji: '🇨🇺' },
  { isoCode: 'JM', name: 'Jamaica', flagEmoji: '🇯🇲' },
  { isoCode: 'HT', name: 'Haití', flagEmoji: '🇭🇹' },
  { isoCode: 'DO', name: 'República Dominicana', flagEmoji: '🇩🇴' },
  { isoCode: 'PR', name: 'Puerto Rico', flagEmoji: '🇵🇷' },
  { isoCode: 'BS', name: 'Bahamas', flagEmoji: '🇧🇸' },
  { isoCode: 'TT', name: 'Trinidad y Tobago', flagEmoji: '🇹🇹' },
  { isoCode: 'BB', name: 'Barbados', flagEmoji: '🇧🇧' },
  { isoCode: 'LC', name: 'Santa Lucía', flagEmoji: '🇱🇨' },
  { isoCode: 'GD', name: 'Granada', flagEmoji: '🇬🇩' },
  { isoCode: 'VC', name: 'San Vicente y las Granadinas', flagEmoji: '🇻🇨' },
  { isoCode: 'AG', name: 'Antigua y Barbuda', flagEmoji: '🇦🇬' },
  { isoCode: 'DM', name: 'Dominica', flagEmoji: '🇩🇲' },
  { isoCode: 'KN', name: 'San Cristóbal y Nieves', flagEmoji: '🇰🇳' },
  { isoCode: 'GB', name: 'Reino Unido', flagEmoji: '🇬🇧' },
  { isoCode: 'IE', name: 'Irlanda', flagEmoji: '🇮🇪' },
  { isoCode: 'FR', name: 'Francia', flagEmoji: '🇫🇷' },
  { isoCode: 'ES', name: 'España', flagEmoji: '🇪🇸' },
  { isoCode: 'PT', name: 'Portugal', flagEmoji: '🇵🇹' },
  { isoCode: 'AD', name: 'Andorra', flagEmoji: '🇦🇩' },
  { isoCode: 'MC', name: 'Mónaco', flagEmoji: '🇲🇨' },
  { isoCode: 'BE', name: 'Bélgica', flagEmoji: '🇧🇪' },
  { isoCode: 'NL', name: 'Países Bajos', flagEmoji: '🇳🇱' },
  { isoCode: 'LU', name: 'Luxemburgo', flagEmoji: '🇱🇺' },
  { isoCode: 'CH', name: 'Suiza', flagEmoji: '🇨🇭' },
  { isoCode: 'LI', name: 'Liechtenstein', flagEmoji: '🇱🇮' },
  { isoCode: 'DE', name: 'Alemania', flagEmoji: '🇩🇪' },
  { isoCode: 'AT', name: 'Austria', flagEmoji: '🇦🇹' },
  { isoCode: 'IT', name: 'Italia', flagEmoji: '🇮🇹' },
  { isoCode: 'SM', name: 'San Marino', flagEmoji: '🇸🇲' },
  { isoCode: 'VA', name: 'Vaticano', flagEmoji: '🇻🇦' },
  { isoCode: 'MT', name: 'Malta', flagEmoji: '🇲🇹' },
  { isoCode: 'IS', name: 'Islandia', flagEmoji: '🇮🇸' },
  { isoCode: 'NO', name: 'Noruega', flagEmoji: '🇳🇴' },
  { isoCode: 'SE', name: 'Suecia', flagEmoji: '🇸🇪' },
  { isoCode: 'FI', name: 'Finlandia', flagEmoji: '🇫🇮' },
  { isoCode: 'DK', name: 'Dinamarca', flagEmoji: '🇩🇰' },
  { isoCode: 'PL', name: 'Polonia', flagEmoji: '🇵🇱' },
  { isoCode: 'CZ', name: 'República Checa', flagEmoji: '🇨🇿' },
  { isoCode: 'SK', name: 'Eslovaquia', flagEmoji: '🇸🇰' },
  { isoCode: 'HU', name: 'Hungría', flagEmoji: '🇭🇺' },
  { isoCode: 'RO', name: 'Rumania', flagEmoji: '🇷🇴' },
  { isoCode: 'BG', name: 'Bulgaria', flagEmoji: '🇧🇬' },
  { isoCode: 'MD', name: 'Moldavia', flagEmoji: '🇲🇩' },
  { isoCode: 'UA', name: 'Ucrania', flagEmoji: '🇺🇦' },
  { isoCode: 'BY', name: 'Bielorrusia', flagEmoji: '🇧🇾' },
  { isoCode: 'RU', name: 'Rusia', flagEmoji: '🇷🇺' },
  { isoCode: 'GR', name: 'Grecia', flagEmoji: '🇬🇷' },
  { isoCode: 'AL', name: 'Albania', flagEmoji: '🇦🇱' },
  { isoCode: 'MK', name: 'Macedonia del Norte', flagEmoji: '🇲🇰' },
  { isoCode: 'RS', name: 'Serbia', flagEmoji: '🇷🇸' },
  { isoCode: 'ME', name: 'Montenegro', flagEmoji: '🇲🇪' },
  { isoCode: 'BA', name: 'Bosnia y Herzegovina', flagEmoji: '🇧🇦' },
  { isoCode: 'HR', name: 'Croacia', flagEmoji: '🇭🇷' },
  { isoCode: 'SI', name: 'Eslovenia', flagEmoji: '🇸🇮' },
  { isoCode: 'XK', name: 'Kosovo', flagEmoji: '🇽🇰' },
  { isoCode: 'EE', name: 'Estonia', flagEmoji: '🇪🇪' },
  { isoCode: 'LV', name: 'Letonia', flagEmoji: '🇱🇻' },
  { isoCode: 'LT', name: 'Lituania', flagEmoji: '🇱🇹' },
  { isoCode: 'TR', name: 'Turquía', flagEmoji: '🇹🇷' },
  { isoCode: 'CY', name: 'Chipre', flagEmoji: '🇨🇾' },
  { isoCode: 'SY', name: 'Siria', flagEmoji: '🇸🇾' },
  { isoCode: 'LB', name: 'Líbano', flagEmoji: '🇱🇧' },
  { isoCode: 'IL', name: 'Israel', flagEmoji: '🇮🇱' },
  { isoCode: 'PS', name: 'Palestina', flagEmoji: '🇵🇸' },
  { isoCode: 'JO', name: 'Jordania', flagEmoji: '🇯🇴' },
  { isoCode: 'IQ', name: 'Irak', flagEmoji: '🇮🇶' },
  { isoCode: 'KW', name: 'Kuwait', flagEmoji: '🇰🇼' },
  { isoCode: 'SA', name: 'Arabia Saudita', flagEmoji: '🇸🇦' },
  { isoCode: 'BH', name: 'Baréin', flagEmoji: '🇧🇭' },
  { isoCode: 'QA', name: 'Catar', flagEmoji: '🇶🇦' },
  { isoCode: 'AE', name: 'Emiratos Árabes Unidos', flagEmoji: '🇦🇪' },
  { isoCode: 'OM', name: 'Omán', flagEmoji: '🇴🇲' },
  { isoCode: 'YE', name: 'Yemen', flagEmoji: '🇾🇪' },
  { isoCode: 'IR', name: 'Irán', flagEmoji: '🇮🇷' },
  { isoCode: 'AM', name: 'Armenia', flagEmoji: '🇦🇲' },
  { isoCode: 'AZ', name: 'Azerbaiyán', flagEmoji: '🇦🇿' },
  { isoCode: 'GE', name: 'Georgia', flagEmoji: '🇬🇪' },
  { isoCode: 'KZ', name: 'Kazajistán', flagEmoji: '🇰🇿' },
  { isoCode: 'UZ', name: 'Uzbekistán', flagEmoji: '🇺🇿' },
  { isoCode: 'TM', name: 'Turkmenistán', flagEmoji: '🇹🇲' },
  { isoCode: 'TJ', name: 'Tayikistán', flagEmoji: '🇹🇯' },
  { isoCode: 'KG', name: 'Kirguistán', flagEmoji: '🇰🇬' },
  { isoCode: 'AF', name: 'Afganistán', flagEmoji: '🇦🇫' },
  { isoCode: 'PK', name: 'Pakistán', flagEmoji: '🇵🇰' },
  { isoCode: 'IN', name: 'India', flagEmoji: '🇮🇳' },
  { isoCode: 'LK', name: 'Sri Lanka', flagEmoji: '🇱🇰' },
  { isoCode: 'MV', name: 'Maldivas', flagEmoji: '🇲🇻' },
  { isoCode: 'NP', name: 'Nepal', flagEmoji: '🇳🇵' },
  { isoCode: 'BT', name: 'Bután', flagEmoji: '🇧🇹' },
  { isoCode: 'BD', name: 'Bangladés', flagEmoji: '🇧🇩' },
  { isoCode: 'MM', name: 'Myanmar', flagEmoji: '🇲🇲' },
  { isoCode: 'TH', name: 'Tailandia', flagEmoji: '🇹🇭' },
  { isoCode: 'LA', name: 'Laos', flagEmoji: '🇱🇦' },
  { isoCode: 'KH', name: 'Camboya', flagEmoji: '🇰🇭' },
  { isoCode: 'VN', name: 'Vietnam', flagEmoji: '🇻🇳' },
  { isoCode: 'MY', name: 'Malasia', flagEmoji: '🇲🇾' },
  { isoCode: 'SG', name: 'Singapur', flagEmoji: '🇸🇬' },
  { isoCode: 'BN', name: 'Brunéi', flagEmoji: '🇧🇳' },
  { isoCode: 'ID', name: 'Indonesia', flagEmoji: '🇮🇩' },
  { isoCode: 'TL', name: 'Timor Oriental', flagEmoji: '🇹🇱' },
  { isoCode: 'PH', name: 'Filipinas', flagEmoji: '🇵🇭' },
  { isoCode: 'CN', name: 'China', flagEmoji: '🇨🇳' },
  { isoCode: 'MN', name: 'Mongolia', flagEmoji: '🇲🇳' },
  { isoCode: 'KP', name: 'Corea del Norte', flagEmoji: '🇰🇵' },
  { isoCode: 'KR', name: 'Corea del Sur', flagEmoji: '🇰🇷' },
  { isoCode: 'JP', name: 'Japón', flagEmoji: '🇯🇵' },
  { isoCode: 'TW', name: 'Taiwán', flagEmoji: '🇹🇼' },
  { isoCode: 'HK', name: 'Hong Kong', flagEmoji: '🇭🇰' },
  { isoCode: 'MO', name: 'Macao', flagEmoji: '🇲🇴' },
  { isoCode: 'EG', name: 'Egipto', flagEmoji: '🇪🇬' },
  { isoCode: 'LY', name: 'Libia', flagEmoji: '🇱🇾' },
  { isoCode: 'TN', name: 'Túnez', flagEmoji: '🇹🇳' },
  { isoCode: 'DZ', name: 'Argelia', flagEmoji: '🇩🇿' },
  { isoCode: 'MA', name: 'Marruecos', flagEmoji: '🇲🇦' },
  { isoCode: 'EH', name: 'Sáhara Occidental', flagEmoji: '🇪🇭' },
  { isoCode: 'MR', name: 'Mauritania', flagEmoji: '🇲🇷' },
  { isoCode: 'SD', name: 'Sudán', flagEmoji: '🇸🇩' },
  { isoCode: 'SS', name: 'Sudán del Sur', flagEmoji: '🇸🇸' },
  { isoCode: 'SN', name: 'Senegal', flagEmoji: '🇸🇳' },
  { isoCode: 'GM', name: 'Gambia', flagEmoji: '🇬🇲' },
  { isoCode: 'GW', name: 'Guinea-Bisáu', flagEmoji: '🇬🇼' },
  { isoCode: 'GN', name: 'Guinea', flagEmoji: '🇬🇳' },
  { isoCode: 'SL', name: 'Sierra Leona', flagEmoji: '🇸🇱' },
  { isoCode: 'LR', name: 'Liberia', flagEmoji: '🇱🇷' },
  { isoCode: 'CI', name: 'Costa de Marfil', flagEmoji: '🇨🇮' },
  { isoCode: 'ML', name: 'Mali', flagEmoji: '🇲🇱' },
  { isoCode: 'BF', name: 'Burkina Faso', flagEmoji: '🇧🇫' },
  { isoCode: 'NE', name: 'Níger', flagEmoji: '🇳🇪' },
  { isoCode: 'NG', name: 'Nigeria', flagEmoji: '🇳🇬' },
  { isoCode: 'BJ', name: 'Benín', flagEmoji: '🇧🇯' },
  { isoCode: 'TG', name: 'Togo', flagEmoji: '🇹🇬' },
  { isoCode: 'GH', name: 'Ghana', flagEmoji: '🇬🇭' },
  { isoCode: 'TD', name: 'Chad', flagEmoji: '🇹🇩' },
  { isoCode: 'CF', name: 'República Centroafricana', flagEmoji: '🇨🇫' },
  { isoCode: 'CM', name: 'Camerún', flagEmoji: '🇨🇲' },
  { isoCode: 'GQ', name: 'Guinea Ecuatorial', flagEmoji: '🇬🇶' },
  { isoCode: 'GA', name: 'Gabón', flagEmoji: '🇬🇦' },
  { isoCode: 'CG', name: 'República del Congo', flagEmoji: '🇨🇬' },
  { isoCode: 'CD', name: 'República Democrática del Congo', flagEmoji: '🇨🇩' },
  { isoCode: 'AO', name: 'Angola', flagEmoji: '🇦🇴' },
  { isoCode: 'ER', name: 'Eritrea', flagEmoji: '🇪🇷' },
  { isoCode: 'ET', name: 'Etiopía', flagEmoji: '🇪🇹' },
  { isoCode: 'DJ', name: 'Yibuti', flagEmoji: '🇩🇯' },
  { isoCode: 'SO', name: 'Somalia', flagEmoji: '🇸🇴' },
  { isoCode: 'KE', name: 'Kenia', flagEmoji: '🇰🇪' },
  { isoCode: 'UG', name: 'Uganda', flagEmoji: '🇺🇬' },
  { isoCode: 'RW', name: 'Ruanda', flagEmoji: '🇷🇼' },
  { isoCode: 'BI', name: 'Burundi', flagEmoji: '🇧🇮' },
  { isoCode: 'TZ', name: 'Tanzania', flagEmoji: '🇹🇿' },
  { isoCode: 'MZ', name: 'Mozambique', flagEmoji: '🇲🇿' },
  { isoCode: 'MW', name: 'Malaui', flagEmoji: '🇲🇼' },
  { isoCode: 'ZM', name: 'Zambia', flagEmoji: '🇿🇲' },
  { isoCode: 'ZW', name: 'Zimbabue', flagEmoji: '🇿🇼' },
  { isoCode: 'MG', name: 'Madagascar', flagEmoji: '🇲🇬' },
  { isoCode: 'MU', name: 'Mauricio', flagEmoji: '🇲🇺' },
  { isoCode: 'SC', name: 'Seychelles', flagEmoji: '🇸🇨' },
  { isoCode: 'KM', name: 'Comoras', flagEmoji: '🇰🇲' },
  { isoCode: 'NA', name: 'Namibia', flagEmoji: '🇳🇦' },
  { isoCode: 'BW', name: 'Botsuana', flagEmoji: '🇧🇼' },
  { isoCode: 'ZA', name: 'Sudáfrica', flagEmoji: '🇿🇦' },
  { isoCode: 'LS', name: 'Lesoto', flagEmoji: '🇱🇸' },
  { isoCode: 'SZ', name: 'Esuatini', flagEmoji: '🇸🇿' },
  { isoCode: 'AU', name: 'Australia', flagEmoji: '🇦🇺' },
  { isoCode: 'NZ', name: 'Nueva Zelanda', flagEmoji: '🇳🇿' },
  { isoCode: 'PG', name: 'Papúa Nueva Guinea', flagEmoji: '🇵🇬' },
  { isoCode: 'FJ', name: 'Fiyi', flagEmoji: '🇫🇯' },
  { isoCode: 'SB', name: 'Islas Salomón', flagEmoji: '🇸🇧' },
  { isoCode: 'VU', name: 'Vanuatu', flagEmoji: '🇻🇺' },
  { isoCode: 'NC', name: 'Nueva Caledonia', flagEmoji: '🇳🇨' },
  { isoCode: 'PF', name: 'Polinesia Francesa', flagEmoji: '🇵🇫' },
  { isoCode: 'WS', name: 'Samoa', flagEmoji: '🇼🇸' },
  { isoCode: 'TO', name: 'Tonga', flagEmoji: '🇹🇴' },
  { isoCode: 'KI', name: 'Kiribati', flagEmoji: '🇰🇮' },
  { isoCode: 'TV', name: 'Tuvalu', flagEmoji: '🇹🇻' },
  { isoCode: 'NR', name: 'Nauru', flagEmoji: '🇳🇷' },
  { isoCode: 'PW', name: 'Palaos', flagEmoji: '🇵🇼' },
  { isoCode: 'FM', name: 'Micronesia', flagEmoji: '🇫🇲' },
  { isoCode: 'MH', name: 'Islas Marshall', flagEmoji: '🇲🇭' },
  { isoCode: 'GU', name: 'Guam', flagEmoji: '🇬🇺' },
  { isoCode: 'AS', name: 'Samoa Americana', flagEmoji: '🇦🇸' },
  { isoCode: 'MP', name: 'Islas Marianas del Norte', flagEmoji: '🇲🇵' },
];

export const timezones = [
  { id: 1, ianaName: 'Etc/GMT+12', utcOffset: -12.0, displayName: 'UTC-12:00 (Baker Island)' },
  { id: 2, ianaName: 'Pacific/Midway', utcOffset: -11.0, displayName: 'UTC-11:00 (Samoa)' },
  { id: 3, ianaName: 'Pacific/Honolulu', utcOffset: -10.0, displayName: 'UTC-10:00 (Hawaii)' },
  { id: 4, ianaName: 'America/Anchorage', utcOffset: -9.0, displayName: 'UTC-09:00 (Alaska)' },
  { id: 5, ianaName: 'America/Los_Angeles', utcOffset: -8.0, displayName: 'UTC-08:00 (PST - Pacífico)' },
  { id: 6, ianaName: 'America/Denver', utcOffset: -7.0, displayName: 'UTC-07:00 (MST - Montaña)' },
  { id: 7, ianaName: 'America/Chicago', utcOffset: -6.0, displayName: 'UTC-06:00 (CST - Central)' },
  { id: 8, ianaName: 'America/New_York', utcOffset: -5.0, displayName: 'UTC-05:00 (EST - Este)' },
  { id: 9, ianaName: 'America/Caracas', utcOffset: -4.0, displayName: 'UTC-04:00 (AST - Atlántico)' },
  { id: 10, ianaName: 'America/Sao_Paulo', utcOffset: -3.0, displayName: 'UTC-03:00 (BRT - Brasil)' },
  { id: 11, ianaName: 'Atlantic/South_Georgia', utcOffset: -2.0, displayName: 'UTC-02:00 (Georgia del Sur)' },
  { id: 12, ianaName: 'Atlantic/Azores', utcOffset: -1.0, displayName: 'UTC-01:00 (Azores)' },
  { id: 13, ianaName: 'UTC', utcOffset: 0.0, displayName: 'UTC±00:00 (Greenwich)' },
  { id: 14, ianaName: 'Europe/Paris', utcOffset: 1.0, displayName: 'UTC+01:00 (CET - Europa Central)' },
  { id: 15, ianaName: 'Europe/Athens', utcOffset: 2.0, displayName: 'UTC+02:00 (EET - Europa Este)' },
  { id: 16, ianaName: 'Europe/Moscow', utcOffset: 3.0, displayName: 'UTC+03:00 (MSK - Moscú)' },
  { id: 17, ianaName: 'Asia/Dubai', utcOffset: 4.0, displayName: 'UTC+04:00 (GST - Golfo)' },
  { id: 18, ianaName: 'Asia/Karachi', utcOffset: 5.0, displayName: 'UTC+05:00 (PKT - Pakistán)' },
  { id: 19, ianaName: 'Asia/Dhaka', utcOffset: 6.0, displayName: 'UTC+06:00 (BST - Bangladesh)' },
  { id: 20, ianaName: 'Asia/Bangkok', utcOffset: 7.0, displayName: 'UTC+07:00 (ICT - Indochina)' },
  { id: 21, ianaName: 'Asia/Shanghai', utcOffset: 8.0, displayName: 'UTC+08:00 (CST - China)' },
  { id: 22, ianaName: 'Asia/Tokyo', utcOffset: 9.0, displayName: 'UTC+09:00 (JST - Japón)' },
  { id: 23, ianaName: 'Australia/Sydney', utcOffset: 10.0, displayName: 'UTC+10:00 (AEST - Australia Este)' },
  { id: 24, ianaName: 'Pacific/Auckland', utcOffset: 12.0, displayName: 'UTC+12:00 (NZST - Nueva Zelanda)' },
];
